server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/backcity
    username: backcity
    password: backcity
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

graphql:
  playground:
    enabled: true
    endpoint: /graphql
    static-base-path: /playground